# ABOUTME: Daily Diagnostics Tab for GNSS-IR Dashboard.
# ABOUTME: Provides quickLook diagnostic plots (LSP, RH vs azimuth) for any processed day.

"""
This tab provides access to expert-level diagnostic plots generated by the
quickLook command, showing Lomb-Scargle Periodograms and reflector height
vs. azimuth plots for any processed day.

Features:
- Date selection interface for choosing specific days
- Side-by-side display of LSP and summary diagnostic plots
- Integration with existing data loading infrastructure
- Clear messaging for days without available plots
"""

import streamlit as st
import pandas as pd
from pathlib import Path
from datetime import datetime, date, timedelta
from PIL import Image
import sys

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.append(str(project_root))

# Import data loading functions
from dashboard_components.data_loader import (
    get_available_diagnostic_days,
    get_quicklook_plots_for_day,
    doy_to_date,
    date_to_doy,
)

from dashboard_components.constants import ENHANCED_COLORS


def display_annual_polar_plots(station_id, year):
    """Display polar plots showing annual retrieval patterns."""
    results_dir = project_root / "results_annual" / station_id

    # Define the three polar plot types
    polar_plots = {
        "polar_quality": {
            "file": results_dir / f"{station_id}_{year}_polar_quality.png",
            "title": "Retrieval Distribution by Azimuth",
            "description": """
            **Left**: Colored by signal amplitude (v/v) - brighter = stronger reflection
            **Right**: Colored by peak-to-noise ratio - higher = cleaner signal
            """,
        },
        "azimuth_analysis": {
            "file": results_dir / f"{station_id}_{year}_azimuth_analysis.png",
            "title": "Azimuth-Dependent Quality Metrics",
            "description": """
            Shows how measurement characteristics vary by look direction:
            - **Top Left**: Number of retrievals per azimuth sector
            - **Top Right**: Measurement variability (lower = more consistent)
            - **Bottom Left**: Signal amplitude by direction
            - **Bottom Right**: Signal quality (PkNoise) by direction
            """,
        },
        "quality_vs_accuracy": {
            "file": results_dir / f"{station_id}_{year}_quality_vs_accuracy.png",
            "title": "Quality Metrics vs Measurement Accuracy",
            "description": """
            Correlation between signal quality and measurement errors:
            - **Top**: Amplitude and PkNoise vs absolute residual
            - **Bottom**: Arc duration effects and azimuthal bias patterns
            """,
        },
    }

    # Check which plots are available
    available_plots = {key: info for key, info in polar_plots.items() if info["file"].exists()}

    if not available_plots:
        st.info(f"""
        📊 **Polar plots not yet generated for {station_id} {year}**

        To generate these plots, run:
        ```bash
        python scripts/plot_azimuth_analysis.py --station {station_id} --year {year}
        ```
        """)
        return

    # Display available plots in expandable sections
    for key, info in available_plots.items():
        with st.expander(f"🎯 {info['title']}", expanded=(key == "polar_quality")):
            st.markdown(info["description"])

            try:
                image = Image.open(info["file"])
                st.image(image, caption=f"{station_id} {year} - {info['title']}", width="stretch")
            except Exception as e:
                st.error(f"Error loading plot: {e}")

    st.success(f"✓ Displaying {len(available_plots)}/3 polar analysis plots")


def render_diagnostics_tab(station_id="FORA", year=2024, data_dict=None):
    """
    Render the Daily Diagnostics tab with QuickLook plot viewer.

    Args:
        station_id: Station identifier (e.g., 'FORA', 'VALR')
        year: Year to display data for
        data_dict: Dictionary containing loaded station data
    """

    st.header("🔍 Diagnostics - Quality Analysis")

    # === Annual Polar Plots Section ===
    st.subheader("📊 Annual Quality Overview - Polar Plots")
    st.markdown("""
    **Spatial Distribution Analysis**: These polar plots show all retrievals for the year,
    revealing azimuth-dependent patterns in signal quality and measurement accuracy.
    """)

    display_annual_polar_plots(station_id, year)

    st.markdown("---")  # Visual separator

    # === Daily Diagnostics Section ===
    st.subheader("�� Daily Diagnostics - QuickLook Plot Viewer")

    st.markdown("""
    **Expert-Level Diagnostic Plots**: View the same diagnostic plots that gnssrefl developers
    use to analyze GNSS-IR data quality. Each day's processing generates two key plots:
    - **Lomb-Scargle Periodogram (LSP)**: Shows the frequency domain analysis used to detect reflector heights
    - **Summary Plot**: Displays reflector height vs. azimuth with quality indicators
    """)

    # Get available diagnostic days
    try:
        available_days = get_available_diagnostic_days(station_id, year)

        if not available_days:
            st.warning(f"📊 No diagnostic plots found for {station_id} {year}")
            st.info("""
            Diagnostic plots are generated during GNSS-IR processing using the `quickLook` command.
            If you see this message, either:
            - No data has been processed for this station/year
            - The processing didn't generate diagnostic plots
            - The plots are stored in a different location
            """)
            return

        st.success(f"📈 Found diagnostic plots for **{len(available_days)} days** in {year}")

        # Initialize session state for DOY if not present
        session_key = f"diagnostics_doy_{station_id}_{year}"
        if session_key not in st.session_state:
            st.session_state[session_key] = available_days[-1]  # Default to most recent

        # Date selection interface
        col1, col2, col3 = st.columns([2, 2, 1])

        with col1:
            # Convert DOY to dates for user-friendly selection
            available_dates = [doy_to_date(year, doy) for doy in available_days]
            min_date = min(available_dates)
            max_date = max(available_dates)

            # Get current DOY from session state
            current_doy = st.session_state[session_key]
            current_date = (
                doy_to_date(year, current_doy) if current_doy in available_days else max_date
            )

            selected_date = st.date_input(
                "📅 Select Date for Diagnostic View",
                value=current_date,
                min_value=min_date,
                max_value=max_date,
                help="Choose a date to view the diagnostic plots generated during processing",
                key=f"diag_date_{station_id}_{year}",
            )

        # Update session state from date input
        selected_doy = date_to_doy(selected_date)
        if selected_doy in available_days:
            st.session_state[session_key] = selected_doy

        with col2:
            # Alternative DOY selection
            current_idx = (
                available_days.index(st.session_state[session_key])
                if st.session_state[session_key] in available_days
                else 0
            )
            doy_input = st.selectbox(
                "🗓️ Or Select by Day of Year (DOY)",
                available_days,
                index=current_idx,
                help="Day of Year (1-365) selection",
                key=f"diag_doy_{station_id}_{year}",
            )

            # Update session state if DOY selection changes
            if doy_input != st.session_state[session_key]:
                st.session_state[session_key] = doy_input
                selected_doy = doy_input
                selected_date = doy_to_date(year, doy_input)

        with col3:
            # Navigation buttons with session state
            st.markdown("**Quick Navigation:**")
            current_idx = (
                available_days.index(st.session_state[session_key])
                if st.session_state[session_key] in available_days
                else 0
            )

            if st.button(
                "⬅️ Previous Day", disabled=current_idx <= 0, key=f"prev_{station_id}_{year}"
            ):
                st.session_state[session_key] = available_days[current_idx - 1]
                st.rerun()

            if st.button(
                "➡️ Next Day",
                disabled=current_idx >= len(available_days) - 1,
                key=f"next_{station_id}_{year}",
            ):
                st.session_state[session_key] = available_days[current_idx + 1]
                st.rerun()

        # Use the session state DOY for display
        selected_doy = st.session_state[session_key]
        selected_date = doy_to_date(year, selected_doy)

        # Display diagnostic plots for selected day
        if selected_doy in available_days:
            display_diagnostic_plots(station_id, year, selected_doy, selected_date)
        else:
            st.warning(
                f"🚫 No diagnostic plots available for {selected_date.strftime('%Y-%m-%d')} (DOY {selected_doy})"
            )

            # Show nearest available days
            st.info("📍 **Nearest available days:**")
            distances = [(abs(doy - selected_doy), doy) for doy in available_days]
            nearest_days = sorted(distances)[:5]

            for _, doy in nearest_days:
                day_date = doy_to_date(year, doy)
                st.write(f"- DOY {doy}: {day_date.strftime('%Y-%m-%d')}")

    except Exception as e:
        st.error(f"❌ Error loading diagnostic data: {str(e)}")
        st.exception(e)


def display_diagnostic_plots(station_id, year, doy, selected_date):
    """Display the LSP and summary plots for a specific day."""

    # Get plot file paths
    plot_files = get_quicklook_plots_for_day(station_id, year, doy)

    if not plot_files:
        st.warning(f"🚫 Plot files not found for DOY {doy}")
        return

    # Display day information
    st.subheader(f"📊 Diagnostic Plots for {selected_date.strftime('%Y-%m-%d')} (DOY {doy})")

    # Create two columns for side-by-side display
    col1, col2 = st.columns(2)

    try:
        # Display Lomb-Scargle Periodogram
        with col1:
            st.markdown("### 🌊 Lomb-Scargle Periodogram (LSP)")
            if "lsp" in plot_files:
                lsp_image = Image.open(plot_files["lsp"])
                st.image(
                    lsp_image, caption=f"LSP Analysis for {station_id} - DOY {doy}", width="stretch"
                )

                # Add explanation
                st.info("""
                **LSP Plot Interpretation:**
                - Shows frequency domain analysis of SNR data
                - Peaks indicate potential reflector heights
                - Higher amplitude peaks = stronger reflections
                - Multiple peaks may indicate multipath or multiple reflection surfaces
                """)
            else:
                st.warning("LSP plot not available")

        # Display Summary Plot
        with col2:
            st.markdown("### 📐 Reflector Height vs. Azimuth")
            if "summary" in plot_files:
                summary_image = Image.open(plot_files["summary"])
                st.image(
                    summary_image,
                    caption=f"Summary Analysis for {station_id} - DOY {doy}",
                    width="stretch",
                )

                # Add explanation
                st.info("""
                **Summary Plot Interpretation:**
                - Shows reflector height estimates vs. satellite azimuth
                - Color indicates signal quality or amplitude
                - Consistent heights across azimuths = good quality
                - Scattered heights = potential multipath or poor conditions
                """)
            else:
                st.warning("Summary plot not available")

        # Add download options
        st.markdown("---")
        st.markdown("### 📥 Download Options")

        download_col1, download_col2 = st.columns(2)

        with download_col1:
            if "lsp" in plot_files:
                with open(plot_files["lsp"], "rb") as file:
                    st.download_button(
                        label="⬇️ Download LSP Plot",
                        data=file.read(),
                        file_name=f"{station_id}_{year}_{doy:03d}_lsp.png",
                        mime="image/png",
                    )

        with download_col2:
            if "summary" in plot_files:
                with open(plot_files["summary"], "rb") as file:
                    st.download_button(
                        label="⬇️ Download Summary Plot",
                        data=file.read(),
                        file_name=f"{station_id}_{year}_{doy:03d}_summary.png",
                        mime="image/png",
                    )

        # Add technical details
        with st.expander("🔧 Technical Details"):
            st.markdown(f"""
            **File Paths:**
            - LSP Plot: `{plot_files.get('lsp', 'Not available')}`
            - Summary Plot: `{plot_files.get('summary', 'Not available')}`
            
            **Processing Information:**
            - Station: {station_id}
            - Year: {year}
            - Day of Year: {doy}
            - Date: {selected_date.strftime('%Y-%m-%d')}
            
            These plots were generated by the `quickLook` command during GNSS-IR processing
            and provide the same diagnostic information used by gnssrefl developers.
            """)

    except Exception as e:
        st.error(f"❌ Error displaying plots: {str(e)}")
        st.exception(e)


# Export function
__all__ = ["render_diagnostics_tab"]
